[package]
name = "techne_project"
version = "0.1.0"
edition = "2021"

[dependencies]
techne-mcp = "0.1.0-dev.2"
techne-server = { version = "0.1.0-dev.2", features = ["http"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3"
